import { useEffect, useState } from "react";
import { ArrowUpRight, Check, ChevronLeft, ChevronRight, Instagram, MapPin, Menu, MessageCircle, Phone, X } from "lucide-react";

const WHATSAPP_NUMBER = "5542988676700";
const WHATSAPP_BASE = `https://wa.me/${WHATSAPP_NUMBER}`;

const specialties = [
  { index: "01", title: "Psicologia", text: "Escuta qualificada para diferentes fases, contextos e necessidades." },
  { index: "02", title: "Nutrição", text: "Orientação alimentar conectada à rotina, saúde e bem-estar." },
  { index: "03", title: "Psicopedagogia", text: "Apoio especializado para aprender, desenvolver e participar." },
  { index: "04", title: "TEA e Autismo", text: "Cuidado multidisciplinar com atenção à singularidade de cada pessoa." },
];

const team = [
  { name: "Veridiana Silveira Wojcickoski", role: "Psicopedagoga", image: "/manus-storage/veridiana_2469b2b9.png", note: "Atendimento psicopedagógico, inclusive para pessoas com TEA." },
  { name: "Maira de Souza Santos", role: "Psicóloga", image: "/manus-storage/meira_9614a40e.png", note: "Trabalho com Terapia Sistêmica." },
  { name: "Andrea Arioli Natel", role: "Psicóloga", image: "/manus-storage/andrea_98975ae5.png", note: "Trabalho com Terapia Cognitivo-Comportamental." },
  { name: "Andréia Regina Lopes", role: "Psicóloga", image: "/manus-storage/andreia_9aa53ca6.png", note: "Trabalho com a Análise do Comportamento." },
  { name: "Rebeca Hostapchn", role: "Psicóloga · CRP 08/43450", image: "/manus-storage/rebeca_7369ee23.png", note: "Terapia Cognitivo-Comportamental e foco em mudanças práticas." },
  { name: "Kamili Schitcoski", role: "Psicóloga especialista em TEA", image: "/manus-storage/kamily_1a70e6cd.png", note: "Atendimento especializado em TEA." },
  { name: "Carla Resende", role: "Podóloga", image: "/manus-storage/carla_6ad8cb6c.png", note: "Podologia preventiva e cuidado com os pés." },
  { name: "Hellen Fernanda", role: "Psicóloga · CRP 08/43808", image: "/manus-storage/hellen_ca3ecd63.png", note: "Saúde mental e acompanhamento psicológico." },
  { name: "Taise Pinheiro", role: "Psicóloga · CRP 03/35040", note: "Nome identificado em publicação pública. Foto e bio oficial aguardam confirmação." },
  { name: "Gabrielle Alves", role: "Fonoaudióloga", note: "Nome associado a publicação pública de Fonoaudiologia. Foto e bio oficial aguardam confirmação." },
];

const agreements = ["GRAM", "Sindicato dos Trabalhadores", "CIM Saúde", "Prever", "Med-Prev", "Tamoyo Prev", "Monte Alegre", "Grebserv"];

const faqs = [
  { question: "Como faço para agendar um atendimento?", answer: "Use qualquer botão de WhatsApp da página. A mensagem será aberta diretamente para a equipe da HCLIN orientar você." },
  { question: "Quais especialidades estão disponíveis?", answer: "A HCLIN divulga Psicologia, Nutrição, Fonoaudiologia, Psicopedagogia, Podologia e atendimentos relacionados a TEA. Confirme a disponibilidade atual pelo WhatsApp." },
  { question: "A HCLIN atende crianças e adolescentes?", answer: "A clínica divulga cuidado relacionado a Psicopedagogia, TEA e Autismo. Fale com a equipe para entender a faixa etária, o profissional indicado e a disponibilidade." },
  { question: "Quais convênios são aceitos?", answer: "Os convênios exibidos nesta página foram identificados em material público fornecido pela clínica. A cobertura pode variar por profissional e procedimento; confirme antes do agendamento." },
  { question: "Onde a clínica está localizada?", answer: "A HCLIN Saúde Integrada está na Av. Eliomar Meira Xavier, 389, em Telêmaco Borba, Paraná." },
];

const carouselItems = [
  { label: "Depoimento real", title: "Seu relato pode aparecer aqui", text: "Espaço reservado para uma avaliação real, autorizada pela pessoa atendida e revisada pela clínica." },
  { label: "Experiência HCLIN", title: "Cuidado que começa pela escuta", text: "O carrossel está pronto para receber avaliações verdadeiras, com identificação e autorização de uso." },
  { label: "Participação da clínica", title: "Envie os depoimentos oficiais", text: "Substitua estes cartões por relatos reais antes da publicação para manter comunicação ética e transparente." },
];

function whatsappLink(message: string) {
  return `${WHATSAPP_BASE}?text=${encodeURIComponent(message)}`;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [form, setForm] = useState({ name: "", interest: "", message: "" });
  const [sent, setSent] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [activeReview, setActiveReview] = useState(0);

  useEffect(() => {
    const timer = window.setInterval(() => setActiveReview((current) => (current + 1) % carouselItems.length), 5200);
    return () => window.clearInterval(timer);
  }, []);

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const text = `Olá, HCLIN! Meu nome é ${form.name}. Tenho interesse em ${form.interest || "conhecer os atendimentos"}.${form.message ? ` ${form.message}` : " Gostaria de saber mais informações e disponibilidade."}`;
    setSent(true);
    window.open(whatsappLink(text), "_blank", "noopener,noreferrer");
  }

  const review = carouselItems[activeReview];

  return (
    <div className="min-h-screen overflow-hidden bg-[#f7f4ed] text-[#17313a]">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-[#17313a]/10 bg-[#f7f4ed]/90 backdrop-blur-xl">
        <div className="mx-auto flex h-[76px] max-w-[1240px] items-center justify-between px-5 lg:px-8">
          <a href="#top" className="flex items-center gap-3" aria-label="HCLIN Saúde Integrada - início"><img src="/manus-storage/hclin-mark_6bbd5686.png" alt="Símbolo H+" className="h-11 w-11 object-contain" /><span className="hidden text-[11px] font-bold uppercase tracking-[0.28em] text-[#0f4c5c] sm:block">HCLIN <span className="font-normal tracking-[0.16em] text-[#9d8152]">saúde integrada</span></span></a>
          <nav className="hidden items-center gap-8 text-[11px] font-bold uppercase tracking-[0.2em] text-[#17313a]/75 md:flex" aria-label="Navegação principal">
            <a className="nav-link" href="#sobre">A HCLIN</a><a className="nav-link" href="#especialidades">Especialidades</a><a className="nav-link" href="#equipe">Equipe</a><a className="nav-link" href="#convenios">Convênios</a><a className="nav-link" href="#avaliacoes">Avaliações</a><a className="nav-link" href="#faq">FAQ</a><a className="nav-link" href="#contato">Contato</a>
          </nav>
          <a href={whatsappLink("Olá, HCLIN! Gostaria de agendar um atendimento.")} target="_blank" rel="noreferrer" className="hidden items-center gap-2 rounded-full bg-[#25D366] px-4 py-2.5 text-[11px] font-bold uppercase tracking-[0.16em] text-white transition hover:-translate-y-0.5 hover:bg-[#1ebc5a] sm:flex"><MessageCircle size={15} /> WhatsApp</a>
          <button className="rounded-full p-2 md:hidden" aria-label={menuOpen ? "Fechar menu" : "Abrir menu"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
        </div>
        {menuOpen && <div className="border-t border-[#17313a]/10 bg-[#f7f4ed] px-5 py-5 md:hidden"><div className="flex flex-col gap-4 text-xs font-bold uppercase tracking-[0.2em]"><a href="#sobre" onClick={() => setMenuOpen(false)}>A HCLIN</a><a href="#especialidades" onClick={() => setMenuOpen(false)}>Especialidades</a><a href="#equipe" onClick={() => setMenuOpen(false)}>Equipe</a><a href="#convenios" onClick={() => setMenuOpen(false)}>Convênios</a><a href="#avaliacoes" onClick={() => setMenuOpen(false)}>Avaliações</a><a href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a><a href="#contato" onClick={() => setMenuOpen(false)}>Contato</a><a className="mt-2 inline-flex items-center gap-2 text-[#128c4a]" href={whatsappLink("Olá, HCLIN! Gostaria de agendar um atendimento.")} target="_blank" rel="noreferrer"><MessageCircle size={15} /> Falar no WhatsApp</a></div></div>}
      </header>

      <main id="top">
        <section className="relative mx-auto grid min-h-[720px] max-w-[1400px] items-center gap-12 px-5 pb-16 pt-32 lg:grid-cols-[0.9fr_1.1fr] lg:px-10 lg:pb-24 lg:pt-40"><div className="relative z-10 max-w-[560px] animate-fade-up"><div className="eyebrow"><span className="eyebrow-line" /> Cuidado conectado em Telêmaco Borba</div><h1 className="mt-7 max-w-[580px] font-display text-[clamp(3.4rem,7vw,6.8rem)] leading-[0.91] tracking-[-0.055em] text-[#0f4c5c]">Mais cuidado <em className="font-normal text-[#9d8152]">conectado</em> à sua rotina.</h1><p className="mt-8 max-w-[440px] text-[17px] leading-8 text-[#17313a]/72">A HCLIN reúne diferentes caminhos de cuidado para que você encontre orientação, escuta e acompanhamento em um só lugar.</p><div className="mt-10 flex flex-wrap items-center gap-4"><a href="#contato" className="inline-flex items-center gap-3 rounded-full bg-[#0f4c5c] px-6 py-3.5 text-xs font-bold uppercase tracking-[0.18em] text-white transition hover:-translate-y-1 hover:bg-[#17313a]">Conversar com a HCLIN <ArrowUpRight size={16} /></a><a href="#especialidades" className="inline-flex items-center gap-2 px-2 py-3 text-xs font-bold uppercase tracking-[0.18em] text-[#0f4c5c] underline decoration-[#c7a96b] underline-offset-8 transition hover:decoration-2">Ver especialidades <ChevronRight size={15} /></a></div></div><div className="relative min-h-[490px] lg:min-h-[600px] animate-fade-in"><div className="absolute -right-16 top-4 h-44 w-44 rounded-full border border-[#c7a96b]/45 lg:right-10" /><div className="absolute -bottom-10 left-0 h-40 w-40 rounded-full border border-[#0f4c5c]/20" /><div className="hero-image absolute inset-y-0 right-0 w-[88%] overflow-hidden rounded-[48%_12%_42%_10%/25%_20%_28%_15%] bg-[#dce5e1]"><img src="/manus-storage/hclin-hero_a21f169d.jpg" alt="Ambiente luminoso de cuidado integrado" className="h-full w-full object-cover" /></div><div className="absolute bottom-6 left-0 flex max-w-[250px] items-start gap-3 rounded-2xl border border-[#17313a]/10 bg-[#f7f4ed]/95 p-4 shadow-[0_20px_60px_rgba(23,49,58,0.12)] backdrop-blur"><span className="mt-1 block h-2 w-2 rounded-full bg-[#c7a96b]" /><p className="text-xs font-medium leading-5 text-[#17313a]/75">Um olhar integrado para cuidar do que importa.</p></div></div></section>
        <section className="border-y border-[#17313a]/10 bg-[#0f4c5c] text-[#f7f4ed]" aria-label="Pilares da HCLIN"><div className="mx-auto flex max-w-[1400px] flex-wrap items-center justify-between gap-5 px-5 py-6 lg:px-10"><span className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#c7a96b]">H+ / presença / cuidado</span><div className="flex flex-wrap gap-x-8 gap-y-2 text-sm text-white/75"><span>Escuta</span><span>Orientação</span><span>Acompanhamento</span><span>Integração</span></div></div></section>
        <section id="sobre" className="mx-auto grid max-w-[1240px] gap-14 px-5 py-24 lg:grid-cols-[0.7fr_1.3fr] lg:px-8 lg:py-36"><div className="lg:pt-6"><div className="eyebrow"><span className="eyebrow-line" /> 01 / A HCLIN</div><h2 className="mt-6 max-w-[380px] font-display text-5xl leading-[0.98] tracking-[-0.04em] text-[#0f4c5c] lg:text-6xl">Cuidado que olha o todo.</h2></div><div className="grid gap-9 lg:grid-cols-[1fr_0.82fr] lg:items-center"><div><p className="text-xl leading-9 text-[#17313a]/80">A HCLIN Saúde Integrada nasce para aproximar diferentes especialidades e tornar o cuidado mais possível, claro e conectado com a vida real.</p><p className="mt-6 text-base leading-8 text-[#17313a]/60">Em Telêmaco Borba, você encontra um espaço para conversar sobre saúde com mais calma e encontrar o caminho de atendimento que faz sentido para o seu momento.</p><a href={whatsappLink("Olá, HCLIN! Gostaria de entender qual atendimento pode fazer sentido para mim.")} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#0f4c5c] underline decoration-[#c7a96b] underline-offset-8">Tirar uma dúvida pelo WhatsApp <ArrowUpRight size={15} /></a></div><div className="relative mx-auto w-full max-w-[330px]"><div className="absolute -inset-3 rounded-[42%_12%_42%_12%] border border-[#c7a96b]/50" /><img src="/manus-storage/hclin-space_b4df1ee6.jpg" alt="Sala de atendimento acolhedora" className="relative aspect-[4/5] w-full rounded-[42%_12%_42%_12%] object-cover" /></div></div></section>
        <section id="especialidades" className="bg-[#e9efea] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1240px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><div className="eyebrow"><span className="eyebrow-line" /> 02 / Caminhos de cuidado</div><h2 className="mt-6 max-w-[600px] font-display text-5xl leading-[0.98] tracking-[-0.045em] text-[#0f4c5c] lg:text-7xl">Encontre o cuidado que combina com você.</h2></div><p className="max-w-[270px] text-sm leading-6 text-[#17313a]/65">A equipe e a disponibilidade podem variar. Fale com a clínica para receber a orientação atualizada.</p></div><div className="relative mt-16 border-t border-[#0f4c5c]/20">{specialties.map((item, itemIndex) => <a key={item.index} href={whatsappLink(`Olá, HCLIN! Tenho interesse em informações sobre ${item.title}.`)} target="_blank" rel="noreferrer" className={`group relative grid gap-5 border-b border-[#0f4c5c]/20 py-7 transition hover:bg-[#f7f4ed]/45 md:grid-cols-[84px_1fr_1.25fr_48px] md:items-center ${itemIndex % 2 === 1 ? "md:pl-16" : "md:pr-16"}`}><span className="relative z-10 flex h-12 w-12 items-center justify-center rounded-full border border-[#c7a96b] bg-[#e9efea] font-mono text-xs text-[#9d8152]">{item.index}</span><h3 className="font-display text-3xl text-[#0f4c5c]">{item.title}</h3><p className="max-w-[410px] text-sm leading-6 text-[#17313a]/65">{item.text}</p><ArrowUpRight size={19} className="text-[#0f4c5c]/40 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#0f4c5c]" />{itemIndex < specialties.length - 1 && <span className="absolute left-[23px] top-[72px] h-8 border-l border-dashed border-[#c7a96b]/70" />}</a>)}</div></div></section>
        <section id="equipe" className="bg-[#f7f4ed] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1240px]"><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><div className="eyebrow"><span className="eyebrow-line" /> 03 / Equipe</div><h2 className="mt-6 max-w-[500px] font-display text-5xl leading-[0.98] tracking-[-0.045em] text-[#0f4c5c] lg:text-7xl">Pessoas que cuidam de pessoas.</h2></div><p className="max-w-[330px] text-sm leading-6 text-[#17313a]/65">Conheça profissionais divulgados nos materiais públicos fornecidos pela clínica. Confirme disponibilidade, registros e especialidades no WhatsApp.</p></div><div className="mt-14 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{team.map((member, index) => <article key={`${member.name}-${index}`} className="group border-t border-[#17313a]/20 pt-4"><div className="relative aspect-[4/5] overflow-hidden rounded-[34%_12%_30%_12%] bg-[#e9efea]"><div className="absolute inset-0 flex items-center justify-center bg-[#e9efea]">{member.image ? <img src={member.image} alt={`Material profissional de ${member.name}`} className="h-full w-full object-cover object-center transition duration-500 group-hover:scale-[1.03]" /> : <div className="flex flex-col items-center justify-center px-7 text-center text-[#0f4c5c]/45"><div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full border border-dashed border-[#9d8152]/70 text-2xl font-display">{index + 1}</div><p className="text-[10px] font-bold uppercase tracking-[0.18em]">Foto reservada</p></div>}</div><div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-[#0f4c5c]/20 to-transparent" /></div><p className="mt-5 text-[10px] font-bold uppercase tracking-[0.2em] text-[#9d8152]">{member.role}</p><h3 className="mt-2 font-display text-2xl leading-tight text-[#0f4c5c]">{member.name}</h3><p className="mt-2 text-xs leading-5 text-[#17313a]/55">{member.note}</p></article>)}</div></div></section>
        <section id="convenios" className="bg-[#0f4c5c] px-5 py-20 text-[#f7f4ed] lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><div className="eyebrow light"><span className="eyebrow-line" /> 04 / Convênios</div><h2 className="mt-6 max-w-[520px] font-display text-5xl leading-[0.98] tracking-[-0.045em] lg:text-6xl">Cuidado mais acessível para a sua rotina.</h2><p className="mt-6 max-w-[450px] text-sm leading-7 text-white/65">A clínica informa atendimento por meio dos convênios abaixo. A cobertura pode variar por profissional, procedimento e plano; confirme antes de agendar.</p><a href={whatsappLink("Olá, HCLIN! Gostaria de confirmar a cobertura do meu convênio.")} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full border border-[#c7a96b]/60 px-5 py-3 text-xs font-bold uppercase tracking-[0.16em] text-[#f7f4ed] transition hover:bg-[#c7a96b] hover:text-[#17313a]">Confirmar meu convênio <ArrowUpRight size={15} /></a></div><div className="grid gap-3 sm:grid-cols-2"><div className="overflow-hidden rounded-[28px] border border-white/15 bg-white/10"><img src="/manus-storage/convenios_b4a287dc.png" alt="Material público com convênios atendidos pela HCLIN" className="h-72 w-full object-cover object-center" /></div><div className="grid grid-cols-2 gap-3">{agreements.map((agreement) => <div key={agreement} className="flex min-h-20 items-center justify-center rounded-2xl border border-white/15 bg-white/5 px-3 text-center text-sm font-semibold text-white/85">{agreement}</div>)}</div></div></div></section>
        <section id="avaliacoes" className="bg-[#f7f4ed] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><div className="eyebrow"><span className="eyebrow-line" /> 05 / Avaliações</div><h2 className="mt-6 max-w-[430px] font-display text-5xl leading-[0.98] tracking-[-0.045em] text-[#0f4c5c] lg:text-6xl">A escuta também continua depois do atendimento.</h2><p className="mt-6 max-w-[370px] text-sm leading-7 text-[#17313a]/65">O carrossel abaixo está preparado para receber avaliações reais, autorizadas e revisadas pela clínica. Nenhum relato foi inventado nesta versão.</p></div><div className="relative min-h-[300px] rounded-[36px] bg-[#e9efea] p-8 sm:p-12"><div className="eyebrow"><span className="eyebrow-line" /> {review.label}</div><div key={activeReview} className="animate-fade-in"><h3 className="mt-8 max-w-[520px] font-display text-4xl leading-tight text-[#0f4c5c]">{review.title}</h3><p className="mt-5 max-w-[520px] text-lg leading-8 text-[#17313a]/70">{review.text}</p></div><div className="absolute bottom-8 left-8 right-8 flex items-center justify-between"><div className="flex gap-2" aria-label={`Slide ${activeReview + 1} de ${carouselItems.length}`}>{carouselItems.map((_, index) => <button key={index} type="button" aria-label={`Ir para o slide ${index + 1}`} onClick={() => setActiveReview(index)} className={`h-2 rounded-full transition-all ${activeReview === index ? "w-8 bg-[#0f4c5c]" : "w-2 bg-[#9d8152]/50"}`} />)}</div><div className="flex gap-2"><button type="button" aria-label="Avaliação anterior" onClick={() => setActiveReview((activeReview - 1 + carouselItems.length) % carouselItems.length)} className="rounded-full border border-[#0f4c5c]/20 p-2 text-[#0f4c5c] transition hover:bg-[#f7f4ed]"><ChevronLeft size={17} /></button><button type="button" aria-label="Próxima avaliação" onClick={() => setActiveReview((activeReview + 1) % carouselItems.length)} className="rounded-full border border-[#0f4c5c]/20 p-2 text-[#0f4c5c] transition hover:bg-[#f7f4ed]"><ChevronRight size={17} /></button></div></div></div></div></section>
        <section className="relative overflow-hidden bg-[#f7f4ed] px-5 py-24 lg:px-10 lg:py-32"><img src="/manus-storage/hclin-pattern_fcb4f8ae.jpg" alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-30 mix-blend-multiply" /><div className="relative mx-auto grid max-w-[1240px] items-center gap-12 lg:grid-cols-[1.2fr_0.8fr]"><div><div className="eyebrow"><span className="eyebrow-line" /> 06 / Como chegar</div><h2 className="mt-6 max-w-[650px] font-display text-5xl leading-[0.98] tracking-[-0.045em] text-[#0f4c5c] lg:text-7xl">Um espaço para cuidar com mais presença.</h2><div className="mt-10 flex items-start gap-4"><MapPin className="mt-1 text-[#9d8152]" size={22} /><div><p className="font-bold text-[#0f4c5c]">Av. Eliomar Meira Xavier, 389</p><p className="mt-1 text-sm text-[#17313a]/65">Telêmaco Borba — Paraná</p></div></div></div><div className="rounded-[28px] border border-[#0f4c5c]/15 bg-[#f7f4ed]/80 p-7 backdrop-blur"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-[#9d8152]">Para começar</p><p className="mt-4 font-display text-3xl leading-tight text-[#0f4c5c]">Conte o que você precisa. A gente orienta o próximo passo.</p><a href="#contato" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#0f4c5c] underline decoration-[#c7a96b] underline-offset-8">Abrir formulário <ChevronRight size={16} /></a></div></div></section>
        <section id="faq" className="bg-[#e9efea] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><div className="eyebrow"><span className="eyebrow-line" /> 07 / Perguntas frequentes</div><h2 className="mt-6 max-w-[420px] font-display text-5xl leading-[0.98] tracking-[-0.045em] text-[#0f4c5c] lg:text-6xl">Antes de conversar, tire suas dúvidas.</h2><p className="mt-6 max-w-[330px] text-sm leading-6 text-[#17313a]/65">Respostas iniciais para orientar sua chegada. Se precisar, a equipe continua a conversa pelo WhatsApp.</p></div><div className="border-t border-[#0f4c5c]/20">{faqs.map((faq, index) => { const isOpen = openFaq === index; return <div key={faq.question} className="border-b border-[#0f4c5c]/20"><button type="button" aria-expanded={isOpen} aria-controls={`faq-answer-${index}`} onClick={() => setOpenFaq(isOpen ? null : index)} className="flex w-full items-center justify-between gap-6 py-6 text-left"><span className="font-display text-2xl text-[#0f4c5c]">{faq.question}</span><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-[#c7a96b] text-xl font-light text-[#9d8152] transition-transform duration-300 ${isOpen ? "rotate-45" : ""}`}>+</span></button><div id={`faq-answer-${index}`} className={`grid transition-[grid-template-rows,opacity] duration-300 ease-out ${isOpen ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"}`}><div className="overflow-hidden"><p className="max-w-[620px] pb-6 pr-14 text-sm leading-7 text-[#17313a]/65">{faq.answer}</p></div></div></div>; })}</div></div></section>
        <section id="contato" className="bg-[#0f4c5c] px-5 py-24 text-[#f7f4ed] lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[1240px] gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-24"><div><div className="eyebrow light"><span className="eyebrow-line" /> 08 / Vamos conversar</div><h2 className="mt-6 max-w-[500px] font-display text-5xl leading-[0.98] tracking-[-0.045em] lg:text-7xl">Seu cuidado começa com uma conversa.</h2><p className="mt-7 max-w-[390px] text-base leading-8 text-white/65">Preencha o formulário. Ao enviar, você será direcionado para o WhatsApp da HCLIN com uma mensagem pronta.</p><div className="mt-9 space-y-3 text-sm text-white/75"><p className="flex items-center gap-3"><Phone size={16} className="text-[#c7a96b]" /> (42) 98867-6700</p><p className="flex items-center gap-3"><MapPin size={16} className="text-[#c7a96b]" /> Telêmaco Borba, Paraná</p></div></div><form onSubmit={handleSubmit} className="rounded-[28px] bg-[#f7f4ed] p-6 text-[#17313a] shadow-2xl sm:p-9"><div className="grid gap-5 sm:grid-cols-2"><label className="field-label sm:col-span-2">Seu nome<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Como podemos chamar você?" /></label><label className="field-label sm:col-span-2">Tenho interesse em<select required value={form.interest} onChange={(e) => setForm({ ...form, interest: e.target.value })}><option value="">Selecione uma opção</option>{specialties.map((item) => <option key={item.title}>{item.title}</option>)}<option value="Fonoaudiologia">Fonoaudiologia</option><option value="Podologia">Podologia</option><option value="Outro atendimento">Outro atendimento</option></select></label><label className="field-label sm:col-span-2">Mensagem <span className="font-normal normal-case tracking-normal text-[#17313a]/40">(opcional)</span><textarea value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Escreva uma dúvida ou conte brevemente o que você procura." rows={4} /></label></div><button type="submit" className="mt-6 flex w-full items-center justify-center gap-3 rounded-full bg-[#25D366] px-6 py-4 text-xs font-bold uppercase tracking-[0.18em] text-white transition hover:-translate-y-1 hover:bg-[#1ebc5a]"><MessageCircle size={17} /> {sent ? "Abrir novamente no WhatsApp" : "Enviar para o WhatsApp"}</button><div className="mt-4 flex items-start gap-2 text-[11px] leading-5 text-[#17313a]/50"><Check size={14} className="mt-0.5 shrink-0 text-[#128c4a]" /> Seus dados não ficam armazenados nesta página. O envio acontece diretamente no WhatsApp.</div></form></div></section>
      </main>
      <footer className="bg-[#0a3945] px-5 py-9 text-white/60 lg:px-10"><div className="mx-auto flex max-w-[1240px] flex-col justify-between gap-6 md:flex-row md:items-center"><div className="flex items-center gap-3"><img src="/manus-storage/hclin-mark_6bbd5686.png" alt="Símbolo H+" className="h-10 w-10 object-contain" /><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-white">HCLIN</p><p className="mt-1 text-[10px] uppercase tracking-[0.18em] text-[#c7a96b]">Saúde integrada</p></div></div><div className="flex flex-wrap items-center gap-5 text-xs"><a className="footer-link" href="https://www.instagram.com/hclin_integrada/" target="_blank" rel="noreferrer"><Instagram size={15} /> Instagram</a><a className="footer-link" href={WHATSAPP_BASE} target="_blank" rel="noreferrer"><MessageCircle size={15} /> WhatsApp</a><span>© 2026 HCLIN</span></div></div></footer>
      <a href={whatsappLink("Olá, HCLIN! Gostaria de falar com a equipe.")} target="_blank" rel="noreferrer" aria-label="Falar com a HCLIN pelo WhatsApp" className="whatsapp-float fixed bottom-5 right-5 z-50 flex items-center gap-3 rounded-full bg-[#25D366] px-4 py-3.5 text-white shadow-[0_12px_35px_rgba(37,211,102,.35)] transition hover:-translate-y-1 hover:bg-[#1ebc5a] sm:bottom-7 sm:right-7"><MessageCircle size={20} /><span className="hidden text-[11px] font-bold uppercase tracking-[0.14em] sm:inline">Falar no WhatsApp</span></a>
    </div>
  );
}
